repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-toml
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.3
    hooks:
    -   id: check-github-actions
    -   id: check-github-workflows
