repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-toml
    -   id: check-yaml
    -   id: double-quote-string-fixer
-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    -   id: black
-   repo: https://github.com/python-poetry/poetry
    rev: 1.6.1
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.0
    hooks:
    -   id: check-github-actions
    -   id: check-github-workflows
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
