name: Build
on: [push]
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: poetry env info
      - run: poetry install
