name: Build & Test
on: [push]
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
          cache: 'poetry'
      - run: poetry install
      - run: cd tests && poetry run coverage run -m pytest
