name: Build and test
on: [push]
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry install
      - run:  poetry run python kilombo/core.py
